version: '3.7'

services:
  db:
    container_name: books_db
    image: postgres
    ports:
      - 5434:5432
    networks:
      - private-network
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: '1234'
      POSTGRES_DB: 'books_db'

volumes:
  pgdata:
    name: books_db

networks:
  private-network:
    name: books
